---

 # create the directory before mounting the volume
    - file:
        path: "{{ gluster_mount_dir }}"
        state: directory
        mode: 0755


    - name: fstab configuration
#    shell: sudo su -c 'echo "localhost:/gv0 /mnt/gluster/uk glusterfs defaults,_netdev,backupvolfile-server=$(hostname) 0 0" >> /etc/fstab'
#    register: fstab
#  - debug: msg="{{fstab.stdout}}"
      mount:
        path: "{{ gluster_mount_dir }}"
        src: "{{ mount_src}}"
        fstype: glusterfs
        opts: "defaults,_netdev,backupvolfile-server={{ inventory_hostname }}"
        dump: 0
        passno: 0
        state: mounted
        register: mount_output
    - debug: msg="{{mount_output}}"
